apiVersion: apps/v1
kind: Deployment
metadata:
  name: hosting-data-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hosting-data
  template:
    metadata:
      labels:
        app: hosting-data
    spec:
      containers:
        - name: nginx
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 8080
